version: '3.4'
services:
  zk_server:
   image: zookeeper:3.4
   ports:
    - 2181:2181
  dubbo-admin:
   image: apache/dubbo-admin:latest
   environment:
       - admin.root.user.name=root
       - admin.root.user.password=root
       - dubbo.registry.address=zookeeper://zookeeper:2181
   links:
    - zk_server:zookeeper
   depends_on:
    - zk_server
   ports:
    - 8080:8080
